import:
  - ~/DevEnv/config/alacritty/dracula.yml
shell:
  program: /usr/local/bin/tmux
  args:
    - new-session
    - -A
    - -D
    - -s
    - main
window:
  padding:
    x: 6
    y: 6
  decorations: full
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 11.0
draw_bold_text_with_bright_colors: true
selection:
  save_to_clipboard: true
dynamic_title: true
