require("utils")
require("plugins")
require("settings")
require("configs.treesitter")
require("configs.auto-session")
require("configs.autopairs")
require("configs.bufferline")
require("configs.gitsigns")
require("configs.lualine")
require("configs.whichkey")
require("configs.mason")
require("configs.mini")
require("configs.telescope")
require("lsp.lsp")
require("lsp.formatter")

require("keymapping")
