local whichkey = require("which-key")

whichkey.register({
	["<leader>"] = {
		b = {
			name = "+Buffer",
			C = {
				name = "+Close",
				j = { "<cmd>BufferlineCloseRight<CR>", "Close buffers to the right" },
				k = { "<cmd>BufferLineCloseLeft<CR>", "Close buffers to the left" },
			},
			c = { "<cmd>BufDel<CR>", "Close current buffer" },
			f = { "<cmd>Telescope buffers<CR>", "List buffers" },
			j = { "<cmd>BufferLineNext<CR>", "Next buffer" },
			k = { "<cmd>BufferLinePrev<CR>", "Previous buffer" },
			s = {
				name = "+Split",
				h = { "<cmd>split<CR>", "Horizontal split" },
				v = { "<cmd>vs<CR>", "Vertical split" },
			},
		},
		-- c = {
		-- 	name = "+Copilot",
		-- 	i = { "<cmd>CopilotChatInPlace<CR>", "In-place code", mode = "x" },
		-- 	R = { "<cmd>CopilotCharReset<CR>", "Reset chat history and clear buffer" },
		-- 	t = { "<cmd>CopilotChatTests<CR>", "Generate tests", mode = "x" },
		-- 	u = { "<cmd>UpdateRemotePlugins<CR>", "Update remote plugins" },
		-- 	v = { "<cmd>CopilotChatVisual<CR>", "Open in vertical split", mode = "x" },
		-- },
		g = {
			name = "+Gitsigns",
			d = { "<cmd>Gitsigns toggle_deleted<CR>", "Toggle deleted" },
			h = { "<cmd>Gitsigns select_hunk<CR>", "Select hunk" },
			j = { "<cmd>Gitsigns next_hunk<CR>", "Next hunk" },
			k = { "<cmd>Gitsigns prev_hunk<CR>", "Previous hunk" },
			p = { "<cmd>Gitsigns preview_hunk<CR>", "Preview hunk" },
			r = { "<cmd>Gitsigns reset_hunk<CR>", "Reset hunk" },
			R = { "<cmd>Gitsigns reset_buffer<CR>", "Reset buffer" },
			s = { "<cmd>Gitsigns stage_hunk<CR>", "Stage hunk" },
			S = { "<cmd>Gitsigns stage_buffer<CR>", "Stage buffer" },
			u = { "<cmd>Gitsigns undo_stage_hunk<CR>", "Undo stage hunk" },
		},
		h = { "<cmd>checkhealth<CR>", "Run health check" },
		l = {
			name = "+LSP",
			a = { "<cmd>lua vim.lsp.buf.code_action()<CR>", "Code actions" },
			d = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Goto definition" },
			D = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Goto declaration" },
			f = { "<cmd>FormatWrite<CR>", "Format current buffer" },
			i = { "<cmd>LspInfo<CR>", "Info" },
			j = { "<cmd>lua vim.diagnostic.goto_next()<CR>", "Next diagnostic" },
			k = { "<cmd>lua vim.diagnostic.goto_prev()<CR>", "Previous diagnostic" },
			r = { "<cmd>lua vim.lsp.buf.rename()<CR>", "Rename" },
			R = { "<cmd>lua vim.diagnostic.reset()<CR>", "Reset diagnostics" },
			t = { "<cmd>Trouble<CR>", "List all current diagnostcis" },
			v = {
				name = "+VenvSelect",
				c = { "<cmd>VenvSelectCached<CR>", "Pick previously used env" },
				s = { "<cmd>VenvSelect<CR>", "Pick an env" },
			},
		},
		m = {
			name = "+Mason",
			m = { "<cmd>Mason<CR>", "List all packages" },
			u = { "<cmd>MasonUpdate<CR>", "Update all packages" },
		},
		n = {
			name = "+Noice",
			a = { "<cmd>Noice<CR>", "Display all message history" },
			l = { "<cmd>Noice last<CR>", "Display last message in a popup" },
		},
		p = {
			name = "+Lazy",
			l = { "<cmd>Lazy<CR>", "List all packages" },
			u = { "<cmd>Lazy update<CR>", "Update packages" },
		},
		q = { "<cmd>confirm q<CR>", "Quit current window" },
		Q = { "<cmd>confirm qa<CR>", "Quit Neovim" },
		s = {
			name = "+Split",
			h = { "<cmd>split<CR>", "Horizontal split" },
			v = { "<cmd>vs<CR>", "Vertical split" },
		},
		t = {
			name = "+Telescope",
			a = { "<cmd>Telescope session-lens<CR>", "List existing sessions" },
			b = { "<cmd>Telescope current_buffer_fuzzy_find<CR>", "Search in current buffer" },
			B = { "<cmd>Telescope buffers<CR>", "List buffers" },
			e = { "<cmd>Telescope file_browser<CR>", "Browse files" },
			f = { "<cmd>Telescope find_files<CR>", "Find files" },
			g = { "<cmd>Telescope live_grep<CR>", "Search words in project" },
			h = { "<cmd>Telescope help_tags<CR>", "Browse help tags" },
			s = { "<cmd>Telescope lsp_document_symbols<CR>", "Document symbols" },
			S = { "<cmd>Telescope lsp_dynamic_workspace_symbols<CR>", "Workspace symbols" },
		},
		w = { "<cmd>w!<CR>", "Save" },
	},
	K = { "<cmd>lua vim.lsp.buf.hover()<CR>", "Show hover" },
	g = {
		D = { "<cmd>lua vim.lsp.buf.declaration()<CR>", "Goto declaration" },
		d = { "<cmd>lua vim.lsp.buf.definition()<CR>", "Goto definition" },
	},
})
